# Generated by Django 4.2.7 on 2023-12-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meseros1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meseros1',
            old_name='nacionalidad',
            new_name='pais',
        ),
        migrations.AddField(
            model_name='meseros1',
            name='dni',
            field=models.CharField(default='00000000', max_length=9),
        ),
    ]
